version: "3"
services:
  app:
    container_name: nodejs-mongo
    restart: always
    build: ./
    environment:
    - MONGO="mongodb://mongo/op_chat"
    ports:
      - "3256:3256"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.2.0
    ports:
      - "27017:27017"