version: "3"
services:
  app:
    container_name: nodejs-mongo
    restart: always
    build: ./
    environment:
    - MONGO=mongodb://root:r56dsert!21@mongo/op_chat?authSource=admin
    ports:
      - 3256:3256
    volumes:
      - .:/app

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: minor
      ME_CONFIG_BASICAUTH_PASSWORD: k82ksalkd!21
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: r56dsert!21
    networks:
      - mongo-compose-network

  mongo:
    container_name: mongo
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: r56dsert!21
    ports:
      - 27017:27017
    volumes:
      - MongoDB:/data/db
    networks:
      - mongo-compose-network

volumes:
  MongoDB:

networks: 
    mongo-compose-network: